name: Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    environment: e2e-tests
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Check Chrome Version
        run: chrome --version
      - name: Install dependencies
        run: npm ci
      - name: Unit Test
        run: npm run cypress:run

        env:
          ## DEBUG: '@cypress/github-action, cypress:*'
          CYPRESS_INVALID_USERNAME: ${{ secrets.CYPRESS_INVALID_USERNAME }}
          CYPRESS_USERNAME: ${{secrets.CYPRESS_USERNAME}}
          CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}